dist: xenial # Ubuntu 16.04
language: clojure
jdk:
    - openjdk8
    - openjdk10

# https://github.com/travis-ci/travis-ci/issues/3897
branches:
    only:
        - master
        - /\d+\.\d+\.\d+/
jobs:
    include:
        # run the release stage 
        # when the branch being tested is 'master'
        # and the revision has been tagged
        -   
            stage: release
            jdk: openjdk8
            #if: branch = master
            script: lein uberjar
            deploy:
                provider: releases
                api_key: 
                    secure: "fWgPeTUUnQY85WeD33ogvj9hZU23k/aqQa6oai2Bdf1wR7rQXw8bwHqEbZrV8kQyp3CUV70Ewjsj2t/cXdOeBGJrionaC95uRYEuAZ8wxjEztyu0Bo19SURi2E9g+shfKqPjxrOJH5UV76FamFRad6IHPpvffFslWb/N7EBhJEHQ9BYcBzfY8Q2PYaaiJSwthkPe/MrdcQOqQdAKtlVevCsAD/JgSN4SWeJaEjOsAZDSxK8uMUmaIzkrV1TSf0k2jGfVarbACxysu4hH+sbpsoSHiKXBjrgdiIxTDbAbfdOI+TzY7dVw/miYcHGExdDZt6Fi+AT1fo8cdQMoKUxIzYMYRHjPXoY0x3doB9DxLUa/XjuyBc+4pMh4At4SRJ8U445rchPd6Vv6wSZbBMnz7GneokVp3BD41/13eUuZtn1arCWdrq3zYmHwjmiiv+nKci72QXyDLz2J37TeiCq9fTLWqQvyIITiLT+gtKdQbPofkvnhOY6zOb1S+r5ArxwNKy65T4giwjX6yEEUDo0lz3hQsCsPinEKGAN2o1FNOxMzCQPEpvwx1m8xTgvcCifW9NcHds084eiCLinQWdNTp92xpNodP2gk7qn1P6eFVVVoBK6jfx4p8W1EQltwfHt8Zq+sdpVMAQMIx+pB30uO+em3ffIPZgDMmttfn8xIjjg="
                file_glob: true
                file: "target/wowman-*-standalone.jar" # target/wowman-1.1.1-standalone.jar
                skip_cleanup: true
                # disabled until I get this working
                #on:
                #    tags: true
