dist: xenial # Ubuntu 16.04

language: clojure
jdk:
    - openjdk11

services:
  - xvfb

script: ./run-tests.sh

# https://github.com/travis-ci/travis-ci/issues/3897
#branches:
#    only:
#        - master
#        - /\d+\.\d+\.\d+/

jobs:
    include:
        # run the release stage 
        # when the branch being tested is 'master'
        # and the revision has been tagged
        -   
            stage: release
            jdk: openjdk11
            if: tag IS present
            script: ./release.sh
            deploy:
                provider: releases
                api_key: $GITHUB_TOKEN
                file_glob: true
                file: 
                    - "target/strongbox-*-standalone.jar" # target/strongbox-1.1.1-standalone.jar
                    - "target/strongbox-*-standalone.jar.sha256" # target/strongbox-1.1.1-standalone.jar.sha256
                skip_cleanup: true
                # redundant if "if: tag is present" ?
                on:
                    tags: true
