dist: xenial # Ubuntu 16.04
language: clojure
jdk:
    - openjdk8
    - openjdk10

services:
  - xvfb

# https://github.com/travis-ci/travis-ci/issues/3897
#branches:
#    only:
#        - master
#        - /\d+\.\d+\.\d+/

jobs:
    include:
        # run the release stage 
        # when the branch being tested is 'master'
        # and the revision has been tagged
        -   
            stage: release
            jdk: openjdk8
            if: tag IS present
            script: lein uberjar
            deploy:
                provider: releases
                api_key: $GITHUB_TOKEN
                file_glob: true
                file: "target/wowman-*-standalone.jar" # target/wowman-1.1.1-standalone.jar
                skip_cleanup: true
                # redundant if "if: tag is present" ?
                on:
                    tags: true
